import type {
  DestinationMetricsSummary,
  LocalMetric,
  ProposalDraft,
  PublishEvent,
  ReviewProposal,
  RoleLane,
  SummaryMetric,
} from './types'

// Static copy for panels that are not yet API-backed (role lanes, metric/summary
// placeholders, publish timeline). Proposal data itself comes from the live API.

// Dev-only seed used when VITE_LOVV_USE_SAMPLE_DATA=true and no real session token
// is present, so the dashboard and charts can be previewed without a backend.
// Never used when a real access token is available.
export const sampleProposals: ReviewProposal[] = [
  {
    id: 'sample-1',
    code: 'PRP-1001',
    title: '제주 동백 군락지 겨울 투어',
    proposerRole: 'R-LOCAL-OPERATOR',
    region: '제주',
    status: 'submitted',
    submittedAt: '2026-06-21T02:10:00Z',
    evidence: '지역 관광협회 추천, 방문객 만족도 4.6/5',
  },
  {
    id: 'sample-2',
    code: 'PRP-1002',
    title: '부산 야간 해안 산책 코스',
    proposerRole: 'R-LOCAL-OPERATOR',
    region: '부산',
    status: 'submitted',
    submittedAt: '2026-06-22T05:30:00Z',
    evidence: '해운대구 보행 데이터 기반',
  },
  {
    id: 'sample-3',
    code: 'PRP-1003',
    title: '전주 한옥마을 미식 페스티벌',
    proposerRole: 'R-DATA-PROVIDER',
    region: '전주',
    status: 'in_review',
    submittedAt: '2026-06-18T08:00:00Z',
    evidence: '전년 대비 방문 23% 증가',
    reviewedBy: 'admin-002',
  },
  {
    id: 'sample-4',
    code: 'PRP-1004',
    title: '강릉 커피거리 워킹 투어',
    proposerRole: 'R-DATA-PROVIDER',
    region: '강릉',
    status: 'approved',
    submittedAt: '2026-06-12T09:15:00Z',
    evidence: '로컬 카페 12곳 제휴 확정',
    reviewedBy: 'admin-001',
    reviewedAt: '2026-06-15T01:00:00Z',
  },
  {
    id: 'sample-5',
    code: 'PRP-1005',
    title: '경주 신라 야경 라이트워크',
    proposerRole: 'R-LOCAL-OPERATOR',
    region: '경주',
    status: 'published',
    submittedAt: '2026-06-05T03:40:00Z',
    evidence: '문화재청 야간개방 일정 연계',
    reviewedBy: 'admin-001',
    reviewedAt: '2026-06-08T07:20:00Z',
  },
  {
    id: 'sample-6',
    code: 'PRP-1006',
    title: '여수 밤바다 케이블카 패키지',
    proposerRole: 'R-DATA-PROVIDER',
    region: '여수',
    status: 'indexed',
    submittedAt: '2026-05-28T06:00:00Z',
    evidence: '추천 캐시 반영 완료',
    reviewedBy: 'admin-002',
    reviewedAt: '2026-06-02T10:10:00Z',
  },
  {
    id: 'sample-7',
    code: 'PRP-1007',
    title: '속초 새벽 수산시장 체험',
    proposerRole: 'R-LOCAL-OPERATOR',
    region: '속초',
    status: 'rejected',
    submittedAt: '2026-06-10T04:25:00Z',
    evidence: '안전 동선 미흡',
    reviewedBy: 'admin-001',
    reviewedAt: '2026-06-13T02:00:00Z',
    reviewNote: '새벽 혼잡 구간 안전 계획 보완 필요',
  },
  {
    id: 'sample-8',
    code: 'PRP-1008',
    title: '안동 전통 탈춤 워크숍',
    proposerRole: 'R-DATA-PROVIDER',
    region: '안동',
    status: 'change_requested',
    submittedAt: '2026-06-16T07:45:00Z',
    evidence: '무형문화재 연계 기획',
    reviewedBy: 'admin-002',
    reviewedAt: '2026-06-19T05:30:00Z',
    reviewNote: '정원·회차 정보 보강 요청',
  },
  {
    id: 'sample-9',
    code: 'PRP-1009',
    title: '통영 섬 호핑 데이투어',
    proposerRole: 'R-LOCAL-OPERATOR',
    region: '통영',
    status: 'withdrawn',
    submittedAt: '2026-06-08T01:05:00Z',
    evidence: '운항사 사정으로 보류',
  },
]

// Dev-only seed for the Local Metrics panel (same opt-in flag as sampleProposals).
export const sampleDestinationMetrics: DestinationMetricsSummary[] = [
  {
    destinationId: 'dst-jeju',
    cityId: 'jeju-si',
    regionId: '제주',
    dateRange: '2026-06',
    destinationImpressions: 12840,
    destinationDetailOpens: 5210,
    itineraryGenerated: 1980,
    itinerarySaved: 1430,
    officialLinkClicks: 640,
    partnerLinkClicks: 410,
    linkClicks: 1050,
    visitIntentSubmitted: 720,
    visitConfirmed: 318,
    distinctUserCount: 4200,
    minGroupSizeMet: true,
  },
  {
    destinationId: 'dst-busan',
    cityId: 'busan',
    regionId: '부산',
    dateRange: '2026-06',
    destinationImpressions: 9620,
    destinationDetailOpens: 4080,
    itineraryGenerated: 1510,
    itinerarySaved: 1020,
    officialLinkClicks: 510,
    partnerLinkClicks: 360,
    linkClicks: 870,
    visitIntentSubmitted: 560,
    visitConfirmed: 244,
    distinctUserCount: 3100,
    minGroupSizeMet: true,
  },
  {
    destinationId: 'dst-jeonju',
    cityId: 'jeonju',
    regionId: '전주',
    dateRange: '2026-06',
    destinationImpressions: 6310,
    destinationDetailOpens: 2450,
    itineraryGenerated: 880,
    itinerarySaved: 600,
    officialLinkClicks: 300,
    partnerLinkClicks: 210,
    linkClicks: 510,
    visitIntentSubmitted: 330,
    visitConfirmed: 140,
    distinctUserCount: 1900,
    minGroupSizeMet: true,
  },
  {
    destinationId: 'dst-gangneung',
    cityId: 'gangneung',
    regionId: '강릉',
    dateRange: '2026-06',
    destinationImpressions: 4180,
    destinationDetailOpens: 1620,
    itineraryGenerated: 540,
    itinerarySaved: 360,
    officialLinkClicks: 190,
    partnerLinkClicks: 150,
    linkClicks: 340,
    visitIntentSubmitted: 210,
    visitConfirmed: 86,
    distinctUserCount: 1250,
    minGroupSizeMet: true,
  },
  {
    destinationId: 'dst-gyeongju',
    cityId: 'gyeongju',
    regionId: '경주',
    dateRange: '2026-06',
    destinationImpressions: 2740,
    destinationDetailOpens: 980,
    itineraryGenerated: 300,
    itinerarySaved: 190,
    officialLinkClicks: 120,
    partnerLinkClicks: 90,
    linkClicks: 210,
    visitIntentSubmitted: 120,
    visitConfirmed: 44,
    distinctUserCount: 720,
    minGroupSizeMet: true,
  },
  {
    destinationId: 'dst-sokcho',
    cityId: 'sokcho',
    regionId: '속초',
    dateRange: '2026-06',
    destinationImpressions: 980,
    destinationDetailOpens: 320,
    itineraryGenerated: 70,
    itinerarySaved: 40,
    officialLinkClicks: 30,
    partnerLinkClicks: 20,
    linkClicks: 50,
    visitIntentSubmitted: 28,
    visitConfirmed: 9,
    distinctUserCount: 110,
    minGroupSizeMet: false,
  },
]

export const summaryMetrics: SummaryMetric[] = [
  {
    label: '제출 제안',
    value: 'API',
    detail: '백엔드 제안 목록 기준',
    tone: 'amber',
  },
  {
    label: '승인 완료',
    value: '실시간',
    detail: '승인 상태 전환 반영',
    tone: 'green',
  },
  {
    label: '반려/수정 요청',
    value: '이력',
    detail: '검토 이력으로 추적',
    tone: 'red',
  },
  {
    label: '반영 상태',
    value: '다음 단계',
    detail: '승인 데이터 반영 작업에서 연결',
    tone: 'blue',
  },
]

export const roleLanes: RoleLane[] = [
  {
    role: 'R-LOCAL-OPERATOR',
    title: '담당 지역 운영 지표 조회',
    description: '지역 운영자는 담당 지역의 제안과 운영 지표를 조회합니다. 승인·반려 결정은 관리자 권한에서만 처리합니다.',
    responsibilities: ['담당 지역 제안 조회', '지역 운영 지표 확인', '수요 분산/관심도 확인', '데이터 최신성 모니터링'],
  },
  {
    role: 'R-DATA-PROVIDER',
    title: '관광지/축제/체험 데이터 제안',
    description: '데이터 제공자는 공식 근거와 함께 관광 데이터를 제안하고, 제출 이후 검토 상태를 확인합니다.',
    responsibilities: ['관광지/명소 제안', '축제/행사 제안', '체험/액티비티 제안', '공식 링크와 설명 첨부'],
  },
  {
    role: 'R-ADMIN',
    title: '데이터 제안 검토',
    description: '관리자는 제출된 제안의 근거를 확인하고 검토·승인·반려 상태를 변경합니다.',
    responsibilities: ['제안 목록 조회', '검토 시작', '승인/반려 결정', '변경 이력 확인'],
  },
  {
    role: 'R-SUPER-ADMIN',
    title: '고위험 변경 승인',
    description: '슈퍼 관리자는 역할/지역 권한 변경과 월간 후보 일괄 게시 요청을 최종 승인하거나 거절합니다.',
    responsibilities: ['고위험 요청 목록 조회', 'TOTP 재인증 후 승인', '요청자 자기 승인 차단 확인', '결정 사유 기록'],
  },
]

export const localMetrics: LocalMetric[] = [
  { label: '강릉 제안 조회', value: 'API 연동 예정', trend: '+0%' },
  { label: '추천 노출 전환', value: '다음 단계', trend: '+0%' },
  { label: '리뷰 수집', value: '다음 단계', trend: '+0' },
  { label: '데이터 최신성 경고', value: '다음 단계', trend: '-0' },
]

export const proposalDraft: ProposalDraft = {
  type: 'festival',
  title: '강릉 커피축제 공식 정보 갱신',
  region: '강릉',
  evidence: '공식 홈페이지 공지와 운영 일정 링크를 근거로 제출합니다.',
  summary: '강릉 커피축제 일정, 공식 링크, 주요 프로그램 정보를 최신 데이터로 갱신합니다.',
}

export const publishEvents: PublishEvent[] = [
  {
    key: 'approved',
    title: '제안 승인 완료',
    status: 'approved',
    description: '관리자가 제안을 승인하면 이력과 approvedContentHash가 저장됩니다.',
    timestamp: '5번 완료',
  },
  {
    key: 'publish',
    title: '서비스 데이터 반영',
    status: 'published',
    description: '승인 데이터를 실제 추천/월간 여행지 데이터로 반영하는 작업은 다음 단계에서 연결합니다.',
    timestamp: '7번 예정',
  },
  {
    key: 'index',
    title: '추천/RAG 인덱스 갱신',
    status: 'indexed',
    description: '반영된 데이터를 추천 후보와 검색 인덱스에 동기화합니다.',
    timestamp: '7번 이후',
  },
]
